---
- name: Ensure Redis is configured
  template:
      src: redis.conf.j2
      dest: "{{ redis_conf_path }}"
      mode: 0644
  notify: restart redis

- name: Ensure Redis is installed
  apt:
      name: redis
      state: present