---
- name: Install MySQL
  apt:
      name: ['mysql-server', 'python-mysqldb']
      update_cache: yes
      cache_valid_time: 3600
      state: present

- name: Copy mysql config
  copy:
      src: ".my.cnf.j2"
      dest: "{{ mysql_custom_conf_dir }}"
      mode: 0644
      owner: root
      group: root

- name: Start the MySQL service
  service:
      name: mysql
      state: started
      enabled: true

- name: Removes all anonymous user accounts
  no_log: true
  mysql_user:
      name: ''
      host_all: yes
      state: absent
