---
- name: Add Nodesource apt key
  apt_key:
      url: https://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x1655A0AB68576280
      id: "68576280"
      state: present

- name: Add Nodesource repositories for Node.js
  apt_repository:
      repo: "{{ item }}"
      state: present
  with_items:
      - "deb https://deb.nodesource.com/node_{{ nodejs_version }} {{ ansible_distribution_release }} main"
      - "deb-src https://deb.nodesource.com/node_{{ nodejs_version }} {{ ansible_distribution_release }} main"
  register: node_repo

- name: Update apt cache if repo was added
  apt:
      update_cache: yes
  when: node_repo.changed

- name: Ensure Node.js and npm are installed
  apt:
      name: "nodejs={{ nodejs_version|regex_replace('x', '') }}*"
      state: present

- name: Remove cmdtest
  apt:
      name: "cmdtest"
      state: absent

- name: Add Yarn apt key
  apt_key:
      url: "https://dl.yarnpkg.com/debian/pubkey.gpg"
      state: present

- name: Add yarn repository
  apt_repository:
      repo: "deb https://dl.yarnpkg.com/debian/ stable main"
      state: present
  register: yarn_repo

- name: Update apt cache if repo was added.
  apt:
      update_cache: yes
  when: yarn_repo.changed

- name: Ensure yarn is installed
  package:
      name: yarn
      state: present

- name: Install Composer
  apt:
      name: composer

- name: Install Redis
  apt:
      name: redis

- name: Install pecl-apcu php extension
  apt:
      name: php-apcu

- name: Install apcu php extension
  apt:
      name: php-mbstring

- name: Install mbstring php extension
  apt:
      name: php-xml

- name: Install igbinary php extension
  apt:
      name: php-igbinary

- name: Install redis php extension
  apt:
      name: php-redis

- name: Install zip php extension
  apt:
      name: php-zip
